server:
  port: 9000

spring:
  application:
      name: login-service
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://127.0.0.1/~/api-gateway
    username: sa
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true

logging.level:
  org.hibernate.SQL: DEBUG
