server:
  port: 8888

spring:
  cloud:
    config:
      server:
        git:
          #window? ?? file:/// ???? file://
#          uri: file:///${user.home}/Desktop/yhnoh/study/msa-config-property
          uri: https://github.com/yhnoh/spring-msa-config-property
