# 스프링 부트 2.4 이후 부터는 profile 설정 ㅕ변경됨
# http://honeymon.io/tech/2021/01/16/spring-boot-config-data-migration.html

spring:
  application:
    name: user-service
---
server:
  port: 8081

spring:
  config:
    activate:
      on-profile: user1

---

server:
  port: 8082

spring:
  config:
    activate:
      on-profile: user2
