server:
  port: 8889

spring:
  rabbitmq:
    username: guest
    password: guest
    host: localhost
    port: 5672
  config:
    import: "optional:configserver:http://localhost:8888"
#  cloud:
#    config:
#      uri: http://127.0.0.1:8888
management:
  endpoints:
    web:
      exposure:
        include: refresh,bus-refresh

---
server:
  port: 8890

spring:
  config:
    activate:
      on-profile: dev


---
server:
  port: 8891

spring:
  config:
    activate:
      on-profile: real

