server:
  port: 8080

spring:
  application:
    name: api-gateway
  #H2 데이터 베이스 사용
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://127.0.0.1/~/api-gateway
    username: sa
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
  cloud:
    gateway:
      #글로벌 필터 : 모든 필터에서 가장 최 상단에 위치
      default-filters:
        - name: GlobalFilter
          args:
            baseMessage: Spring Cloud Gateway Filter
            preLogger: true
            postLogger: true
      routes:
        # 로그인 서비스
        # 대상 URL은 http://127.0.0.1:9000번 포트이다. http://127.0.0.1:8080 -> http://127.0.0.1:9000
        # /login와 POST방식만 요청 가능
        - id: login-service
          uri: http://127.0.0.1:9000
          predicates:
            - Path=/login
            - Method=POST
        # 유저 서비스
        # /user-service/** -> /user-service/**
        # Weight=group-user, 5 부하 분산을 사용하기 위해서 user-service1에 5, user-service2에 5
        # RewritePath=/user-service/(?<path>.*),/$\{path}, user-service/** -> /** 로 변경
        - id: user-service1
          uri: http://127.0.0.1:8500
          predicates:
           - Path=/user-service/**
           - Weight=group-user, 5
          filters:
           - name: AuthorizationFilter
             args:
               baseMessage: Spring Cloud Gateway Filter
               preLogger: true
               postLogger: true
           - RewritePath=/user-service/(?<path>.*),/$\{path}
        - id: user-service2
          uri: http://127.0.0.1:8501
          predicates:
            - Path=/user-service/**
            - Weight=group-user, 5
          filters:
            - name: AuthorizationFilter
              args:
                baseMessage: Spring Cloud Gateway Filter
                preLogger: true
                postLogger: true
            - RewritePath=/user-service/(?<path>.*),/$\{path}
management:
  endpoints:
    web:
      exposure:
        include:
          - "gateway"
  endpoint:
    gateway:
      enabled: true
